# Generated by Django 5.0.6 on 2024-06-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
